// flow-typed signature: 53d4deee838823b93be6737f4d7639e6
// flow-typed version: <<STUB>>/enzyme-context-patch_v^0.0.7/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-context-patch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-context-patch' {
  declare module.exports: any;
}
